config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_scope :user do
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end


  resources :posts

  resources :users, only: [:show, :index] 
  resources :requests, only: [:new, :create, :show, :destroy] 
  resources :friendships, only: [:new, :create, :show, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :profiles

  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #attributes: user_id, post_id, body
  #you can comment on a post, but not on a comment

  belongs_to :user
  belongs_to :post
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord

  belongs_to :requesting_friend, class_name: 'User' #user sending the friend request
  belongs_to :requested_friend, class_name: 'User' #user receiving the friend request
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  #attributes: user_id, friend_id

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/image_post.rb
class ImagePost < ApplicationRecord
  has_one :post, as: :postable

  has_one_attached :image #optional, otherwise stored in URL
end

app/models/like.rb
class Like < ApplicationRecord
  #attributes: user_id, post_id

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
# Post attributes: title, body

belongs_to :user
has_many :likes
has_many :comments

belongs_to :postable, polymorphic: true



end

app/models/profile.rb
class Profile < ApplicationRecord
  # Post attributes: avatar (as attachment), intro, location
  # just simple stuff for now

  belongs_to :user

  has_one_attached :avatar
end

app/models/request.rb
class Request < ApplicationRecord

  belongs_to :requesting_friend, class_name: 'User' #user sending the friend request
  belongs_to :requested_friend, class_name: 'User' #user receiving the friend request
end

app/models/text_post.rb
class TextPost < ApplicationRecord
  has_one :post, as: :postable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #User attributes: username, name, email, encrypted password

  devise :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      #auth.extra.raw_info.username.present? ? user.username = auth.extra.raw_info.username : user.username = auth.info.first_name
      user.username = auth.info.name
      user.name = auth.info.name   # assuming the user model has a name

      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  has_many :friendships, foreign_key: :user_id, class_name: 'Friendship'
  has_many :friends, through: :friendships

  has_many :sent_friend_requests, foreign_key: :requesting_friend_id, class_name: 'Request'
  has_many :requested_friends, through: :sent_friend_requests

  has_many :received_friend_requests, foreign_key: :requested_friend_id, class_name: 'Request'
  has_many :requesting_friends, through: :received_friend_requests

  has_many :posts
  has_many :likes
  has_many :comments

  has_one :profile

  #after_create :send_welcome_email #temporarily disabled for heroku deployment

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_now
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(user_id: current_user.id, post_id: comment_params[:post_id], body: comment_params[:body])
    
    if @comment.save
        redirect_to root_path, notice: "Comment Created!"
    else
        redirect_to root_path, status: :unprocessable_entity
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to root_path, notice: "Comment deleted"
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  private

  def comment_params 
    params.require(:comment).permit(:body, :post_id)
  end




end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @like = Like.new(user_id: current_user.id, post_id: like_params[:post_id])

    if @like.save
      redirect_to root_path, notice: "Post Liked!"
    else
      redirect_to root_path, status: :unprocessable_entity
    end

  end

  def destroy
    @like = Like.find(params[:id])
    if @like.destroy
      redirect_to root_path, notice: "Post unliked"
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  private
  def like_params
    params.require(:like).permit(:post_id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    @comment = Comment.new
    @posts = Post.where(user_id: current_user).or(Post.where(user_id: current_user.friends)).order("created_at DESC")
  end

  def new
    #new handles image posts - simple text posts are done from index or profile
  end

  def create
    #creates an image post
    if post_params[:post_type] == "image"
      if post_params[:img_url].present?
        @image_post = ImagePost.new(img_url: post_params[:img_url])
      else
        @image_post = ImagePost.new(image: post_params[:image])
      end
      @post = @image_post.build_post(
        title: post_params[:title],
        user_id: current_user.id,
      )
      if @post.save && @image_post.save
        redirect_to root_path, notice: "Image posted sucessfully!"
      else
        render root_path, alert: :unprocessable_entity
      end
    #creates a text post
    else
      @text_post = TextPost.new(body: post_params[:body])
      @post = @text_post.build_post(
        title: post_params[:title],
        user_id: current_user.id,
      )

      if @post.save && @text_post.save
        redirect_to root_path, notice: "Post created sucessfully!"
      else
        render root_path, alert: :unprocessable_entity
      end
    end  
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :img_url, :image, :post_type)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @post = Post.new
    @posts = @user.posts.all.order("created_at DESC")
    @comment = Comment.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_find_friends.html.erb
<section class="section"> 
  <div class="container">
    <div class="content">
      <h1>Find Friends</h1>
      <% @users.each do |user| %>
        <% unless 
            user == current_user || 
            current_user.friends.include?(user) || 
            current_user.requested_friends.include?(user) || 
            current_user.requesting_friends.include?(user) %>
          <div class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                <p class="image is-square is-48x48">
                  <%= image_tag(profile_pic(user), class: "is-rounded") %>
                </p>
              </div>
              <div class="level-item">
                <p><strong><%= link_to user.username, user %></strong></p>
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                <%= link_to "Invite", requests_path(:invitee => user.id), :method => :post, class: "button is-success" %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/_friend_requests.html.erb
<% unless current_user.sent_friend_requests.empty? & current_user.received_friend_requests.empty? %>
  <section class="section"> 
    <div class="container">
      <div class="content">
        <h1>Friend Requests</h1>
        <% unless current_user.sent_friend_requests.empty? %>
          <p class="subtitle">Sent Friend Requests</p>
            <% current_user.sent_friend_requests.each do |request| %>
                <div class="level">
                  <!-- Left side -->
                  <div class="level-left">
                    <div class="level-item">
                      <p class="image is-square is-48x48">
                        <%= image_tag(profile_pic(request.requested_friend), class: "is-rounded") %>
                      </p>
                    </div>
                    <div class="level-item">
                      <p><strong><%= link_to request.requested_friend.username, request.requested_friend %></strong></p>
                    </div>
                  </div>
                  <!-- Right side -->
                  <div class="level-right">
                    <p class="level-item">
                      <%= link_to "Cancel", request_path(request.id), method: :delete, class: "button is-warning" %>
                    </p>
                  </div>
                </div>
            <% end %>
        <% end %>
        <% unless current_user.received_friend_requests.empty? %>
          <p class="subtitle">Received</p>
            <% current_user.received_friend_requests.each do |request| %>
                <div class="level">
                  <!-- Left side -->
                  <div class="level-left">
                    <div class="level-item">
                      <p class="image is-square is-48x48">
                        <%= image_tag(profile_pic(request.requesting_friend), class: "is-rounded") %>
                      </p>
                    </div>
                    <div class="level-item">
                      <p><strong><%= link_to request.requesting_friend.username, request.requesting_friend %></strong></p>
                    </div>
                  </div>

                  <!-- Right side -->
                  <div class="level-right">
                    <p class="level-item">
                      <%= form_for :friendship, url: friendships_path do |f| %>
                        <%= hidden_field_tag(:request_id, request.id) %>
                        <%= f.submit "Accept", class: "button is-success" %> 
                      <!-- deny button only on see more page due to room? -->
                      <% end %>
                    </p>
                  </div>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/users/_friends.html.erb
<% unless @user.friends.empty? %>
  <section class="section"> 
    <div class="container">
      <div class="content">
        <h1>Friends</h1>
            <% @user.friends.each do |friend| %>
                <div class="level">
                  <!-- Left side -->
                  <div class="level-left">
                    <div class="level-item">
                      <p class="image is-square is-48x48">
                        <%= image_tag(profile_pic(friend), class: "is-rounded") %>
                      </p>
                    </div>
                    <div class="level-item">
                      <p><strong><%= link_to friend.username, friend %></strong></p>
                    </div>
                  </div>
                </div>
            <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/users/index.html.erb
<section class="section"> 
  <div class="container">
    <div class="box">
      <div class="content">
        <h1>Find People</h1>
        <% @users.each do |user| %>
          <% unless user == current_user  %>
            <div class="level">
              <!-- Left side -->
              <div class="level-left">
                <div class="level-item">
                  <%= image_tag("default_avatar.png", size: "60x100") %>
                </div>
                <div class="level-item">
                  <p><strong><%= link_to user.username, user %></strong></p>
                </div>
              </div>

              <!-- Right side -->
              <div class="level-right">
                <p class="level-item">
                  <% if current_user.friends.include?(user) %>
                    <!--delete friend -->
                    <%= link_to "Remove Friend", friendship_path(current_user.friendships.find_by(friend_id: user.id)), method: :delete, class: "button is-danger" %>

                  <% elsif current_user.requested_friends.include?(user) %>
                    <%= link_to "Cancel Invite", request_path(current_user.sent_friend_requests.find_by(requested_friend_id: user.id)), method: :delete, class: "button is-warning" %>

                  <% elsif current_user.requesting_friends.include?(user) %>
                    <%= form_for :friendship, url: friendships_path do |f| %>
                      <%= hidden_field_tag(:request_id, current_user.received_friend_requests.find_by(requesting_friend_id: user.id).id) %>
                      <%= f.submit "Accept", class: "button is-success" %> 
                      <%= link_to "Reject Invite", request_path(current_user.received_friend_requests.find_by(requesting_friend_id: user.id)), method: :delete, class: "button is-warning" %>
                    <% end %>

                  <% else %> <!-- not a friend -->
                    <%= link_to "Invite", requests_path(:invitee => user.id), :method => :post, class: "button is-success" %>
                  <% end %>
                </p>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="columns">
  
  <!--profile section on left-->
  <div class="column">
    <section class="section"> 
      <div class="container">
        <div class="content">
          <h1>Profile</h1>
          <% if @user.profile.blank? %>
            <p><%=@user.username%> hasn't created a profile yet</p>
            <%= link_to("create profile", new_profile_path) if @user == current_user %>
          <% else %>
            <figure class="image is-256x256">
              <%= image_tag url_for(@user.profile.avatar) %>
            </figure>
            <p><strong>About me</strong></p>
            <p><%= @user.profile.intro %></p>
            <p><strong>Location</strong></p>
            <p><%= @user.profile.location %></p>

            <%= link_to("update profile", edit_profile_path) if @user == current_user %>
          <% end %>
        </div>
      </div>
    </section>
  </div>

  <!--user's posts in center-->
  <div class="column is-three-fifths">
    <%= render "posts/new_post_form" if @user == current_user %>
    <section class="section">
      <div class="content">
        <h1><%= @user.username %>'s Posts</h1>
        <% @posts.each do |post| %>
          <%= render "posts/post_media", post: post %>
        <% end %>
      </div>
    </section>
  </div>

  <!--friends bar on right-->
  <div class="column">
    <%= render "friends" %>
    <% if @user == current_user %>
      <%= render "friend_requests" %>
      <%= render "find_friends" %>
    <% end %>
  </div>

</div>