config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_scope :user do
  #  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  #end


  resources :posts

  resources :users, only: [:show, :index] 
  resources :requests, only: [:new, :create, :show, :destroy] 
  resources :friendships, only: [:new, :create, :show, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :profiles

  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #attributes: user_id, post_id, body
  #you can comment on a post, but not on a comment

  belongs_to :user
  belongs_to :post
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord

  belongs_to :requesting_friend, class_name: 'User' #user sending the friend request
  belongs_to :requested_friend, class_name: 'User' #user receiving the friend request
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  #attributes: user_id, friend_id

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/image_post.rb
class ImagePost < ApplicationRecord
  has_one :post, as: :postable

  has_one_attached :image #optional, otherwise stored in URL
end

app/models/like.rb
class Like < ApplicationRecord
  #attributes: user_id, post_id

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
# Post attributes: title, body

belongs_to :user
has_many :likes
has_many :comments

belongs_to :postable, polymorphic: true



end

app/models/profile.rb
class Profile < ApplicationRecord
  # Post attributes: avatar (as attachment), intro, location
  # just simple stuff for now

  belongs_to :user

  has_one_attached :avatar
end

app/models/request.rb
class Request < ApplicationRecord

  belongs_to :requesting_friend, class_name: 'User' #user sending the friend request
  belongs_to :requested_friend, class_name: 'User' #user receiving the friend request
end

app/models/text_post.rb
class TextPost < ApplicationRecord
  has_one :post, as: :postable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #User attributes: username, name, email, encrypted password

  devise :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      #auth.extra.raw_info.username.present? ? user.username = auth.extra.raw_info.username : user.username = auth.info.first_name
      user.username = auth.info.name
      user.name = auth.info.name   # assuming the user model has a name

      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  has_many :friendships, foreign_key: :user_id, class_name: 'Friendship'
  has_many :friends, through: :friendships

  has_many :sent_friend_requests, foreign_key: :requesting_friend_id, class_name: 'Request'
  has_many :requested_friends, through: :sent_friend_requests

  has_many :received_friend_requests, foreign_key: :requested_friend_id, class_name: 'Request'
  has_many :requesting_friends, through: :received_friend_requests

  has_many :posts
  has_many :likes
  has_many :comments

  has_one :profile

  #after_create :send_welcome_email #temporarily disabled for heroku deployment

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_now
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(user_id: current_user.id, post_id: comment_params[:post_id], body: comment_params[:body])
    
    if @comment.save
        redirect_to root_path, notice: "Comment Created!"
    else
        redirect_to root_path, status: :unprocessable_entity
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to root_path, notice: "Comment deleted"
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  private

  def comment_params 
    params.require(:comment).permit(:body, :post_id)
  end




end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @like = Like.new(user_id: current_user.id, post_id: like_params[:post_id])

    if @like.save
      redirect_to root_path, notice: "Post Liked!"
    else
      redirect_to root_path, status: :unprocessable_entity
    end

  end

  def destroy
    @like = Like.find(params[:id])
    if @like.destroy
      redirect_to root_path, notice: "Post unliked"
    else
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  private
  def like_params
    params.require(:like).permit(:post_id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    @comment = Comment.new
    @posts = Post.where(user_id: current_user).or(Post.where(user_id: current_user.friends)).order("created_at DESC")
  end

  def new
    #new handles image posts - simple text posts are done from index or profile
  end

  def create
    #creates an image post
    if post_params[:post_type] == "image"
      if post_params[:img_url].present?
        @image_post = ImagePost.new(img_url: post_params[:img_url])
      else
        @image_post = ImagePost.new(image: post_params[:image])
      end
      @post = @image_post.build_post(
        title: post_params[:title],
        user_id: current_user.id,
      )
      if @post.save && @image_post.save
        redirect_to root_path, notice: "Image posted sucessfully!"
      else
        render root_path, alert: :unprocessable_entity
      end
    #creates a text post
    else
      @text_post = TextPost.new(body: post_params[:body])
      @post = @text_post.build_post(
        title: post_params[:title],
        user_id: current_user.id,
      )

      if @post.save && @text_post.save
        redirect_to root_path, notice: "Post created sucessfully!"
      else
        render root_path, alert: :unprocessable_entity
      end
    end  
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :img_url, :image, :post_type)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @post = Post.new
    @posts = @user.posts.all.order("created_at DESC")
    @comment = Comment.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment.html.erb
<article class="media">
  <figure class="media-left mb-0">
    <p class="image is-square is-48x48">
      <%= image_tag(profile_pic(comment.user), class: "is-rounded") %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= link_to "@" + comment.user.username, comment.user %></strong><br>
        <%= comment.body %>   
      </p>
    </div>
  </div>
  <% if comment.user == current_user %>
    <div class="media-right">
        <%= link_to fa_icon("trash"), comment_path(comment), method: "delete", class: "icon is-small" %>
    </div>
  <% end %>
</article>

app/views/posts/_comment_form.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-square is-48x48">
      <%= image_tag(profile_pic(current_user), class: "is-rounded") %>
    </p>
  </figure>
  <div class="media-content">
    <%= form_for @comment do |f| %>
      <div class="field">
        <div class="control">
          <%= f.text_area :body, autofocus: true, placeholder: "Add comment here...", class: "textarea", rows: 2 %>
          <%= f.hidden_field :post_id, value: post.id %>
        </div>
      </div>
      <nav class="level">
        <div class="level-left">
          <div class="level-item">
            <%= f.submit "Submit", class: "button is-link" %> 
          </div>
        </div>
      </nav>
    <% end %>
  </div>
</article>

app/views/posts/_new_post_form.html.erb
<section class="section">
  <div class="container">
    <div class="content">
      <h1>Share Your Thoughts</h1>
      <div class="box">
        <article class="media">
          <figure class="media-left">
              <p class="image is-square is-64x64">
                <%= image_tag profile_pic(current_user), class: "is-rounded" %>
              </p>
          </figure>
          <div class="media-content">
            <%= form_with scope: :post, url: posts_path do |f| %>
              <div class="field">
                <div class="control">
                  <%= f.text_field :title, autofocus: true, placeholder: "New post title", class: "input", required: true %>
                </div>
              </div>
              <div class="field">
                <div class="control">
                  <%= f.text_area :body, autofocus: true, placeholder: "New post content...", class: "textarea", required: true %>
                </div>
              </div>
              <nav class="level">
                <div class="level-left">
                  <div class="level-item">
                    <%= f.submit "Submit", class: "button is-link" %>
                  </div>
                  <div class="level-item">
                    <%= link_to "Post an Image", new_post_path, class: "button is-link is-light" %>
                  </div>
                </div>
              </nav>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/posts/_post_media.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-square is-64x64">
        <%= image_tag(profile_pic(post.user), class: "is-rounded") %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= post.title %></strong> <small><%= link_to post.user.username, post.user %></small> <small><%= time_ago_in_words(post.created_at) %> ago</small>
          <br>
          <% if post.postable.class == ImagePost %>
            <figure class="image">
              <% if post.postable.img_url.present? %>
                <%= image_tag post.postable.img_url %>
              <% else %>
                <%= image_tag post.postable.image %>
              <% end %>
            </figure>
          <% else %>
            <%= post.postable.body %>
          <% end %>
        </p>
      </div>
      <!-- controls for own posts -->
      <% if post.user != current_user %>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <% if post.likes.find_by(user_id: current_user.id) %>
              <%= link_to fa_icon("heart"), like_path(post.likes.find_by(user_id: current_user.id)), method: "delete", class: "icon is-small" %>
            <% else %>
              <%= link_to fa_icon("heart-o"), likes_path(:like => {:post_id => post.id}), method: "post", class: "icon is-small" %>
            <% end %>
          </a>
        </div>
      </nav>
      <% end %>

      <!-- comments section here -->
      <% post.comments.each do |comment| %>
        <%= render "posts/comment", comment: comment %>
      <% end %>
      <%= render "posts/comment_form", post: post %>

    </div>
    <% unless post.likes.count() == 0 %>
      <div class="media-right">
          <span class="icon-text has-text-dark">
            <span class="icon">
              <i class="fa fa-heart"></i>
            </span>
            <span><%= post.likes.count() %></span>
          </span>
      </div>
    <% end %>
    <% if post.user == current_user %>
    <div class="media-right">
        <%= link_to fa_icon("trash"), post_path(post), method: "delete", class: "icon is-small" %>
    </div>
  <% end %>
  </article>
</div>

app/views/posts/index.html.erb
<%= render "new_post_form" %>

<!-- shows an existing post -->
<div class="section">
  <div class="container">
    <div class="content">
      <h1>Timeline</h1>
      <% @posts.each do |post| %>
        <%= render "post_media", post: post %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<section class="section">
  <div class="container">
    <div class="content">
      <h1>Share An Image</h1>
        <%= form_with scope: :post, url: posts_path do |f| %>
          <%= f.hidden_field :post_type, value: "image" %>
          <div class="field">
            <%= f.label "Title", class: "label" %>
            <div class="control">
              <%= f.text_field :title, autofocus: true, class: "input", placeholder: "Title for your post", required: true %>
            </div>
          </div>
          <div class="field">
            <%= f.label "Link to image", class: "label" %>
            <div class="control">
              <%= f.text_field :img_url, class: "input", placeholder: "Add a link to an image, or upload your own (but not both)" %>
            </div>
          </div>
          <div class="field">
            <%= f.label "Upload image", class: "label" %>
            <div class="control">
              <%= f.file_field :image %>
            </div>
          </div>
          <br>
          <div class="field is-grouped">
            <div class="control">
              <%= f.submit "Submit", class: "button is-link" %>
            </div>
            <div class="control">
              <%= link_to "Cancel", user_path(current_user), class: "button is-link is-light" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</section>